/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Igu;
import Logica.ControladoraLogica;

import java.awt.Color;
/**
 *
 * @author villa
 */
public class AltaMascota extends javax.swing.JFrame {
ControladoraLogica controladoraLogica;
    /**
     * Creates new form AltaMascota
     */
    public AltaMascota(ControladoraLogica controlLogica) {
        this.controladoraLogica = controlLogica;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        spNroCliente = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtNombreMascota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNroCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombreDuenio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spNombreMascota = new javax.swing.JSeparator();
        spObservaciones = new javax.swing.JSeparator();
        spRaza = new javax.swing.JSeparator();
        ChkBoxAtencionEspecial = new javax.swing.JCheckBox();
        spColor = new javax.swing.JSeparator();
        ChkBoxAlergico = new javax.swing.JCheckBox();
        spNombreDuenio = new javax.swing.JSeparator();
        spCel = new javax.swing.JSeparator();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        lblGuardar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cliente Nº:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        txtRaza.setBackground(new java.awt.Color(255, 255, 255));
        txtRaza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRaza.setForeground(new java.awt.Color(0, 0, 0));
        txtRaza.setText("Yorkshire");
        txtRaza.setBorder(null);
        txtRaza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazaFocusLost(evt);
            }
        });
        jPanel1.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 20));

        spNroCliente.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spNroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 112, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        txtNombreMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMascota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreMascota.setText("Bruster");
        txtNombreMascota.setBorder(null);
        txtNombreMascota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreMascotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreMascotaFocusLost(evt);
            }
        });
        jPanel1.add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Raza:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        txtNroCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNroCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNroCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNroCliente.setText("1");
        txtNroCliente.setBorder(null);
        txtNroCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNroClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNroClienteFocusLost(evt);
            }
        });
        txtNroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNroClienteMouseClicked(evt);
            }
        });
        jPanel1.add(txtNroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Color:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        txtColor.setBackground(new java.awt.Color(255, 255, 255));
        txtColor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtColor.setForeground(new java.awt.Color(0, 0, 0));
        txtColor.setText("Marron negro blanco");
        txtColor.setBorder(null);
        txtColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorFocusLost(evt);
            }
        });
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre Dueño:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 20));

        txtNombreDuenio.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreDuenio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreDuenio.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreDuenio.setText("Gabriel Villarreal");
        txtNombreDuenio.setBorder(null);
        txtNombreDuenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreDuenioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreDuenioFocusLost(evt);
            }
        });
        jPanel1.add(txtNombreDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 240, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cel. Dueño:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 20));

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        txtCelular.setText("3541 379657");
        txtCelular.setBorder(null);
        txtCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularFocusLost(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 240, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Observaciones:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        txtObservaciones.setBackground(new java.awt.Color(255, 255, 255));
        txtObservaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtObservaciones.setText("No le gusta que le agarren las patas");
        txtObservaciones.setBorder(null);
        txtObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObservacionesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObservacionesFocusLost(evt);
            }
        });
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 240, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/peluqueria_canina.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        spNombreMascota.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 150, 260, -1));

        spObservaciones.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 240, 10));

        spRaza.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 190, 260, 10));

        ChkBoxAtencionEspecial.setBackground(new java.awt.Color(255, 255, 255));
        ChkBoxAtencionEspecial.setForeground(new java.awt.Color(0, 0, 0));
        ChkBoxAtencionEspecial.setText("Atención Especial:");
        ChkBoxAtencionEspecial.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(ChkBoxAtencionEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        spColor.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, 10));

        ChkBoxAlergico.setBackground(new java.awt.Color(255, 255, 255));
        ChkBoxAlergico.setForeground(new java.awt.Color(0, 0, 0));
        ChkBoxAlergico.setText("Alérgico:");
        ChkBoxAlergico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(ChkBoxAlergico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        spNombreDuenio.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spNombreDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 240, 10));

        spCel.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(spCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 240, 10));

        btnLimpiar.setBackground(new java.awt.Color(102, 0, 255));
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 204), 1, true));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(64, 36));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(64, 36));
        btnLimpiar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseMoved(evt);
            }
        });
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpiarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseReleased(evt);
            }
        });
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setText("LIMPIAR");
        lblLimpiar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseMoved(evt);
            }
        });
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarbtnGuardarMouseClicked(evt);
                lblLimpiarjPanel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLimpiarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseReleased(evt);
            }
        });
        btnLimpiar.add(lblLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 100, 36));

        btnGuardar.setBackground(new java.awt.Color(102, 0, 255));
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 204), 1, true));
        btnGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuardarMouseMoved(evt);
            }
        });
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGuardarMouseReleased(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setText("GUARDAR");
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });
        btnGuardar.add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 100, 36));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("INGRESE LOS DATOS DE LA MASCOTA Y SU DUEÑO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusGained
        txtRaza.selectAll();
        spRaza.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtRazaFocusGained

    private void txtNombreMascotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreMascotaFocusGained
        txtNombreMascota.selectAll();
        spNombreMascota.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtNombreMascotaFocusGained

    private void txtNroClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNroClienteFocusGained
        txtNroCliente.selectAll();
        spNroCliente.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtNroClienteFocusGained

    private void txtColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusGained
        txtColor.selectAll();
        spColor.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtColorFocusGained

    private void txtNombreDuenioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDuenioFocusGained
        txtNombreDuenio.selectAll();
        spNombreDuenio.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtNombreDuenioFocusGained

    private void txtCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularFocusGained
        txtCelular.selectAll();
        spCel.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtCelularFocusGained

    private void txtObservacionesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacionesFocusGained
        txtObservaciones.selectAll();
        spObservaciones.setBackground(new Color(255,30,47));
    }//GEN-LAST:event_txtObservacionesFocusGained

    private void lblLimpiarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseMoved
        btnLimpiar.setBackground(new Color(102,0,204));
        lblLimpiar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLimpiarMouseMoved

    private void lblLimpiarbtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarbtnGuardarMouseClicked
        limpiar();
    }//GEN-LAST:event_lblLimpiarbtnGuardarMouseClicked

    private void lblLimpiarjPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarjPanel4MouseClicked
       
    }//GEN-LAST:event_lblLimpiarjPanel4MouseClicked

    private void lblLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseExited
        btnLimpiar.setBackground(new Color(102,51,255));
        lblLimpiar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblLimpiarMouseExited

    private void btnLimpiarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseMoved
        btnLimpiar.setBackground(new Color(102,0,204));
        lblLimpiar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLimpiarMouseMoved

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
       
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        btnLimpiar.setBackground(new Color(102,51,255));
        lblLimpiar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseMoved
         btnGuardar.setBackground(new Color(102,0,204));
    }//GEN-LAST:event_btnGuardarMouseMoved

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        guardar();
        limpiar();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(102,51,255));
        lblGuardar.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        btnGuardar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnGuardarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseReleased
        btnGuardar.setBackground(new Color(102,0,255));
    }//GEN-LAST:event_btnGuardarMouseReleased

    private void txtNroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroClienteMouseClicked
        
    }//GEN-LAST:event_txtNroClienteMouseClicked

    private void txtNroClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNroClienteFocusLost
        spNroCliente.setBackground(new Color(60,63,65));
        
    }//GEN-LAST:event_txtNroClienteFocusLost

    private void txtNombreMascotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreMascotaFocusLost
        spNombreMascota.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtNombreMascotaFocusLost

    private void txtRazaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusLost
        spRaza.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtRazaFocusLost

    private void txtColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusLost
        spColor.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtColorFocusLost

    private void txtNombreDuenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDuenioFocusLost
       spNombreDuenio.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtNombreDuenioFocusLost

    private void txtCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularFocusLost
        spCel.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtCelularFocusLost

    private void txtObservacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacionesFocusLost
        spObservaciones.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_txtObservacionesFocusLost

    private void btnLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMousePressed
        btnLimpiar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_btnLimpiarMousePressed

    private void btnLimpiarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseReleased
        btnLimpiar.setBackground(new Color(102,0,255));
    }//GEN-LAST:event_btnLimpiarMouseReleased

    private void lblLimpiarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseReleased
        btnLimpiar.setBackground(new Color(102,0,255));
    }//GEN-LAST:event_lblLimpiarMouseReleased

    private void lblLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMousePressed
        btnLimpiar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_lblLimpiarMousePressed

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        guardar();
        limpiar();
    }//GEN-LAST:event_lblGuardarMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkBoxAlergico;
    private javax.swing.JCheckBox ChkBoxAtencionEspecial;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JSeparator spCel;
    private javax.swing.JSeparator spColor;
    private javax.swing.JSeparator spNombreDuenio;
    private javax.swing.JSeparator spNombreMascota;
    private javax.swing.JSeparator spNroCliente;
    private javax.swing.JSeparator spObservaciones;
    private javax.swing.JSeparator spRaza;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombreDuenio;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtNroCliente;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
       txtCelular.setText("");
       txtColor.setText("");
       txtNombreDuenio.setText("");
       txtNombreMascota.setText("");
       txtNroCliente.setText("");
       txtObservaciones.setText("");
       txtRaza.setText("");
       ChkBoxAlergico.setSelected(false);
       ChkBoxAtencionEspecial.setSelected(false);
       txtNroCliente.requestFocus();
    }

    private void guardar() {
        String nombreDuenio = txtNombreDuenio.getText();
        String celular = txtCelular.getText();
        String color = txtColor.getText();
        String nombreMascota = txtNombreMascota.getText();
        int nroCliente  = Integer.parseInt(txtNroCliente.getText());
        String observaciones  = txtObservaciones.getText();
        String raza  = txtRaza.getText();
        boolean alergico = (ChkBoxAlergico.isSelected());
        boolean atencionEspecial = (ChkBoxAtencionEspecial.isSelected());
        
        controladoraLogica.crearMascota(nroCliente, nombreMascota, raza, color, alergico, atencionEspecial, nombreDuenio, celular, observaciones);
    }
}
